[package]
name = "frp-gaming-app"
version = "0.1.0"
authors = ["g2xpf <nameko.jack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frp-gaming-lib = { path = "../frp-gaming-lib", version = "0.1.0" }
